# Generated by Django 4.2.4 on 2023-10-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(default='No alt', max_length=255)),
                ('image', models.FileField(upload_to='media/news')),
            ],
        ),
    ]
