# Generated by Django 4.2.4 on 2023-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agadmin', '0002_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='store/news/images/'),
        ),
    ]
