# Generated by Django 4.2.4 on 2023-09-26 11:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_name_category_title_rename_name_type_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
